package by.bsu.dektiarev.action.util;

/**
 * Enum representing command names
 * Created by USER on 25.04.2016.
 */
public enum ActionEnum {
    LOGIN, LOGOUT, GET_TRUCKS, CHANGE_TRUCK_STATE,
    GET_DRIVERS, GET_REQUESTS, GET_TRIPS, GET_TRIPS_BY_DRIVER,
    GET_ASSIGNATION_FORM, ASSIGN_DRIVER_TO_A_TRIP, GET_SIGNUP_FORM, SIGNUP,
    CHANGE_TRIP_STATE, CHAT, GET_MAIN_PAGE, ADD_REQUEST, GET_UNASSIGNED_REQUESTS,
    GET_LOGIN_FORM, DELETE_REQUEST, GET_ERROR_PAGE
}
