package action.util;

/**
 * Enum representing command names
 * Created by USER on 25.04.2016.
 */
enum ActionEnum {
    LOGIN, LOGOUT, GET_TRUCKS, CHANGE_TRUCK_STATE,
    GET_DRIVERS, GET_APPLICATIONS, GET_TRIPS, GET_TRIPS_BY_DRIVER,
    GET_SETTING_FORM, SET_DRIVER_ON_TRIP, SIGNUP_FORM, SIGNUP,
    CHANGE_TRIP_STATE, CHAT
}
